version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - psd_uploads:/app/psd_uploads
      - psd_outputs:/app/psd_outputs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=development-secret-key
      - UPLOAD_FOLDER=/app/psd_uploads
      - OUTPUT_FOLDER=/app/psd_outputs
    restart: unless-stopped

volumes:
  psd_uploads:
  psd_outputs:
